Feature: bc-implementer template: work_done pre-emit precondition (clean tree + work_id on origin/main) for Implementer-emitted paths

  @scenario_hash:fe496a8073f27678 @bc:shopsystem-templates
  Scenario: bc-implementer template directs the implementer to verify the BC's working tree is clean AND the work_id's change is committed to origin/main before emitting work_done (complete) for an Implementer-emitted dispatch (request_maintenance or non-scenario request_bugfix)
    When I read the bc-implementer template via "shop-templates show bc-implementer"
    Then the content names "git status --porcelain" as a pre-emit verification step the implementer must run before composing a work_done with status complete on a dispatch where the Implementer is the work_done emitter (request_maintenance, or request_bugfix whose scenarios[] is empty)
    And the content names "git log" or "git rev-parse" (against the BC's "origin/main" ref) as a pre-emit verification step that confirms the work_id's change is present on the BC's main branch
    And the content directs the implementer that when "git status --porcelain" produces any non-empty output the implementer must NOT emit work_done with status complete, and instead must surface the uncommitted state as a blocker (e.g., emit work_done with status blocked, or stop and report) with the offending paths named in the response summary
    And the content directs the implementer that when the BC's "origin/main" HEAD does NOT carry a commit for the dispatched work_id the implementer must NOT emit work_done with status complete, and instead must surface the missing-commit state as a blocker with the work_id named in the response summary
    And the content marks both checks as discrete pre-emit steps that fire for every Implementer-emitted work_done (complete) regardless of message_type, not as optional guidance the implementer may skip
    And the content makes clear these pre-emit checks do NOT apply to the assign_scenarios / scenario-carrying request_bugfix path, where the Reviewer holds the gate per the existing "Hand-off to the Reviewer" section and per scenarios 105–108 against bc-reviewer

  @scenario_hash:e5669ee6062b95fd @bc:shopsystem-templates
  Scenario: bc-implementer template directs the implementer to block a work_done (complete) emit when tracked files in the BC root are modified but uncommitted, and to name the dirty paths in the response
    When I read the bc-implementer template via "shop-templates show bc-implementer"
    Then the content directs the implementer that, prior to emitting work_done with status complete on a dispatch where the Implementer is the work_done emitter (request_maintenance, or request_bugfix whose scenarios[] is empty), the implementer must invoke "git status --porcelain" in the BC root and inspect its output
    And the content directs the implementer that any line in "git status --porcelain" output with a tracked-file modification marker (lines beginning with " M", "M ", "MM", " D", "D ", "A ", "AM", " R", "R ", " C", "C ", or "UU") is a precondition failure
    And the content directs the implementer that on such a precondition failure the implementer does NOT compose "shop-msg respond work_done --status complete" and instead emits "shop-msg respond work_done --status blocked" with a summary that names the tracked paths reported by "git status --porcelain"
    And the content frames the dirty-tracked-files check as a step the implementer runs even when acceptance criteria are satisfied and any local verification (unit tests, build, lint) passes, so a green local result does not bypass the check

  @scenario_hash:86d576b269ff89d6 @bc:shopsystem-templates
  Scenario: bc-implementer template directs the implementer to block a work_done (complete) emit when untracked files are present in the BC root, and to name the untracked paths in the response
    When I read the bc-implementer template via "shop-templates show bc-implementer"
    Then the content directs the implementer that the same "git status --porcelain" inspection that catches modified-tracked-files (per scenario 110) also catches untracked files (lines beginning with "??") and treats them as a precondition failure on any Implementer-emitted work_done (request_maintenance, or request_bugfix whose scenarios[] is empty)
    And the content directs the implementer that on untracked-files failure the implementer does NOT compose "shop-msg respond work_done --status complete" and instead emits "shop-msg respond work_done --status blocked" with a summary that names the untracked paths reported by "git status --porcelain"
    And the content explicitly directs the implementer that the untracked-files check is NOT satisfied by adding the paths to .gitignore unless the paths are genuinely outside the BC's scope of work; the implementer must confirm by inspection of the dispatch's acceptance criteria (or by clarify back to the lead) whether the untracked paths are work product that should be committed before re-attempting the emit

  @scenario_hash:e01ace6acd655909 @bc:shopsystem-templates
  Scenario: bc-implementer template directs the implementer to block a work_done (complete) emit when the BC's origin/main branch does not carry a commit attributable to the dispatched work_id, and to name the missing work_id and current origin/main HEAD in the response
    When I read the bc-implementer template via "shop-templates show bc-implementer"
    Then the content directs the implementer that, prior to emitting work_done with status complete on a dispatch where the Implementer is the work_done emitter (request_maintenance, or request_bugfix whose scenarios[] is empty), the implementer must verify by "git log origin/main" (or equivalent "git log" against the BC's main branch) that at least one commit attributable to the dispatched work_id is reachable from "origin/main" HEAD
    And the content names a concrete attribution mechanism the implementer may use to recognize the work_id's commit (for example, the work_id substring appearing in the commit message subject or body, or a tag/note pointing at the work_id), so the implementer does not have to invent a convention
    And the content directs the implementer that when no commit attributable to the work_id is reachable from "origin/main" HEAD the implementer does NOT compose "shop-msg respond work_done --status complete" and instead emits "shop-msg respond work_done --status blocked" with a summary that names the dispatched work_id and the current "origin/main" HEAD short SHA
    And the content directs the implementer that committing the work_id's change to any branch OTHER than the BC's main branch (e.g., a local feature branch that has not been merged or pushed to origin/main) does NOT satisfy this precondition; the only outcome that satisfies the precondition is the work_id's commit being reachable from "origin/main" HEAD
    And the content directs the implementer that "git fetch origin" should be run as part of the verification so a stale local view of "origin/main" does not produce a false positive
    And the content explicitly disclaims the BC role-discipline interpretation "BC role discipline does not push" as a reason to skip this check; for Implementer-emitted work_done, pushing the work_id commit to origin/main is part of the work, not optional polish
