Feature: BC reviewer template encodes ADR-010 work_done.scenario_hashes pre-emit check

  @scenario_hash:e0d4c445a0cd7500 @bc:shopsystem-templates
  Scenario: bc-reviewer template directs the reviewer to recompute each hash in work_done.scenario_hashes against the as-committed feature files and to allow the emit only when every hash matches the recomputed value (happy path)
    When I read the bc-reviewer template via "shop-templates show bc-reviewer"
    Then the content directs the reviewer that, before composing "shop-msg respond work_done --status complete" on a scenario-carrying dispatch (assign_scenarios, or request_bugfix whose scenarios[] is non-empty), the reviewer must recompute the hash of every scenario the work_done payload will list in "--scenario-hash" using the canonical "scenarios hash" CLI against the BC's as-committed feature files under "features/"
    And the content directs the reviewer to perform the recomputation in the same BC root state that the prior pre-emit steps (clean working tree, work_id commit on origin/main per scenarios 105-108) have just verified, so the recomputed hashes are taken from the exact bytes that will land on origin/main
    And the content directs the reviewer to also confirm by "grep" (or "git grep") for each hash that an "@scenario_hash:<hash>" tag is present in some file under "features/", per ADR-010's observable-evidence requirement
    And the content directs the reviewer that the work_done emit is allowed to proceed only when every hash the reviewer would pass to "--scenario-hash" satisfies BOTH the recomputation check (the hash equals the value "scenarios hash" produces against the as-committed body) AND the presence check (an "@scenario_hash:<hash>" tag is reachable under "features/")
    And the content marks the recomputation step as a discrete pre-emit step alongside the existing BDD-rerun, working-tree, and work_id-on-origin-main checks, not as optional guidance the reviewer may skip
    And the content cites ADR-010 as the rule the recomputation step is encoding

  @scenario_hash:50174dbb885ff5a8 @bc:shopsystem-templates
  Scenario: bc-reviewer template directs the reviewer to block a work_done (complete) emit when any hash the reviewer would echo in "--scenario-hash" no longer matches the value "scenarios hash" recomputes against the as-committed scenario body (stale hash), and to name the work_id, the stale hash, and the recomputed value in the response
    When I read the bc-reviewer template via "shop-templates show bc-reviewer"
    Then the content directs the reviewer that, when the reviewer recomputes the hash of an as-committed scenario body via "scenarios hash" and the recomputed value differs from the hash the reviewer would otherwise pass to "--scenario-hash" (for instance because the implementer edited the scenario after the dispatch pinned its hash), the divergence is a precondition failure
    And the content directs the reviewer that on such a stale-hash failure the reviewer does NOT compose "shop-msg respond work_done --status complete" and instead emits "shop-msg respond work_done --status blocked"
    And the content directs the reviewer that the response summary on the blocked emit must name the dispatched work_id, the stale hash value (the one the dispatch carried or the reviewer was about to echo), and the recomputed value that "scenarios hash" produced against the as-committed body, so the lead can decide between re-pinning the hash on a fresh dispatch or restoring the scenario body without a round-trip
    And the content frames the stale-hash check as a step the reviewer runs even when the BDD suite passes and even when an "@scenario_hash:<hash>" tag for the stale hash is still grep-able somewhere under "features/", because a stale tag and a green BDD result together do not establish that the wire-form hash describes the body the BC has committed
    And the content cites ADR-010 §4 (observable-evidence requirement, BC-side) as the rule the stale-hash check is encoding

  @scenario_hash:762e847fe873201e @bc:shopsystem-templates
  Scenario: bc-reviewer template directs the reviewer to block a work_done (complete) emit when the work_done payload's "--scenario-hash" list omits a hash for one or more scenarios that the dispatch carried AND that ARE present in the as-committed "features/" tree (missing hash), and to name the work_id and the omitted scenarios in the response
    When I read the bc-reviewer template via "shop-templates show bc-reviewer"
    Then the content directs the reviewer that, before composing "shop-msg respond work_done --status complete", the reviewer must enumerate the scenario hashes the dispatch payload carried (the "@scenario_hash:<hash>" set the lead's dispatch text named) and confirm by "grep" (or "git grep") that each dispatched hash is also reachable under an "@scenario_hash:<hash>" tag in the BC's as-committed "features/" tree
    And the content directs the reviewer that, for every dispatched hash that IS reachable under "features/", that hash MUST appear in the "--scenario-hash" list the reviewer would pass to "shop-msg respond work_done"; omitting such a hash is a precondition failure even when the BDD suite passes and even when the omitted scenario is genuinely pinned on disk
    And the content directs the reviewer that on such a missing-hash failure the reviewer does NOT compose "shop-msg respond work_done --status complete" and instead emits "shop-msg respond work_done --status blocked"
    And the content directs the reviewer that the response summary on the blocked emit must name the dispatched work_id and, for each omitted hash, both the hash value and the path of the feature file under "features/" where the corresponding "@scenario_hash:<hash>" tag is reachable, so the lead can see that the BC pinned the scenarios on disk but composed an incomplete payload
    And the content cites the "echo back every scenario hash that currently passes" direction in the existing "Sign-off" subsection as the rule this check operationalizes, and cites lead-plt as the empirical case it exists to prevent

  @scenario_hash:36d22e52adcea48e @bc:shopsystem-templates
  Scenario: bc-reviewer template directs the reviewer to block a work_done (complete) emit when the work_done payload's "--scenario-hash" list carries a hash that is NOT reachable under any "@scenario_hash:<hash>" tag in the BC's as-committed "features/" tree (extra / orphan hash), and to name the work_id and the orphan hash in the response
    When I read the bc-reviewer template via "shop-templates show bc-reviewer"
    Then the content directs the reviewer that, before composing "shop-msg respond work_done --status complete", the reviewer must confirm by "grep" (or "git grep") for each hash the reviewer would pass to "--scenario-hash" that an "@scenario_hash:<hash>" tag carrying that exact value is reachable in some file under the BC's as-committed "features/" tree
    And the content directs the reviewer that any hash the reviewer would echo for which no such tag is reachable under "features/" is a precondition failure, regardless of whether the dispatch text named the hash, whether the scenario was once pinned on disk and later removed, or whether the hash was composed from elsewhere
    And the content directs the reviewer that on such an orphan-hash failure the reviewer does NOT compose "shop-msg respond work_done --status complete" and instead emits "shop-msg respond work_done --status blocked"
    And the content directs the reviewer that the response summary on the blocked emit must name the dispatched work_id and, for each orphan hash, both the hash value and the explicit statement that no "@scenario_hash:<hash>" tag carrying that value is reachable under "features/", so the lead can decide between asking the BC to restore a removed scenario or correcting the payload without round-tripping
    And the content frames the orphan-hash check as the strict-subset rule ADR-010 §4 makes canonical (work_done.scenario_hashes MUST be a subset of the hashes actually pinned in the BC's features/) and cites ADR-010 as the rule this check is encoding
